import Favicons from "../components/layout/Partials/Favicons"

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta charSet="UTF-8" />
      <Favicons />
    </>
  )
}
